AllCops:
  Exclude:
    - "gemfiles/*"
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Documentation:
  Exclude:
    - "**/railtie.rb"
    - "spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
Layout/LineLength:
  Max: 120
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/RaiseArgs:
  EnforcedStyle: compact
Style/EmptyMethod:
  EnforcedStyle: expanded
Layout/FirstArrayElementIndentation:
  IndentationWidth: 4
Layout/FirstHashElementIndentation:
  IndentationWidth: 4
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
Layout/FirstParameterIndentation:
  IndentationWidth: 4
Layout/MultilineOperationIndentation:
  IndentationWidth: 4
  EnforcedStyle: indented
Style/FormatStringToken:
  EnforcedStyle: template
Style/AsciiComments:
  Enabled: false
Naming/FileName:
  Exclude:
    - "lib/cron-kubernetes.rb"
Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "spec/**/*"

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - "spec/**/*"
